### ISSUE TITLE
TensorLayer书 第一印 97页 VGG数据表格

### ISSUE THREAD

**Issue by Windaway** [tensorlayer/chinese-book#1]
可训练参数
我的理解是每一层特征量，应该不需要，也没标注是内存空间，不需要算为KiB。
参数内存占用（KB）
这里应该是kernelsize*inputchannels*outputchannels+outputchannels乘以4除以1024.
但是书中这个表 感觉上表头和数据计算不严谨

**Comment by Windaway** [comment]
第1列应该是层数？tensor形状第2列？tensor占用内存应该是第3列？可训练参数第四列？

**Comment by Windaway** [comment]
99页第一个GooLeNet拼写错误

**Comment by yiminglin-ai** [comment]
Hi @Windaway , 感谢您的指出,书中表格确实在排版出版的时候遗漏了一行,我已经在PR: https://github.com/tensorlayer/chinese-book/pull/2 
上传了正确表格, 会在下次印刷中改正. 对您造成阅读上的不便深感抱歉, 若此章仍有其它问题我会逐一解答.

**Comment by Windaway** [comment]
@yl1991 99页第一个GooLeNet 拼写错误
