### ISSUE TITLE
ch2.6.3 line 3,4 reuse需要在两个地方设置？

### ISSUE THREAD

**Issue by arisliang** [tensorlayer/chinese-book#10]
似乎有点重复，为什么同样的reuse值需要在两个地方设置呢？
`with tf.variable_scope("MLP", reuse=reuse):`
`tl.layers.set_name_reuse(reuse)`

**Comment by zsdonghao** [comment]
前一个reuse是控制TF的，后一个reuse是控制TL的，不过有可能2.0版本会去掉TL这个设置。

**Comment by arisliang** [comment]
明白了，谢谢
