### ISSUE TITLE
ch3.6 p77 line 84 module 'tensorlayer.visualize' has no attribute 'W'

### ISSUE THREAD

**Issue by arisliang** [tensorlayer/chinese-book#14]
可视化第一层W错误时运行错误，没有tf.visualize.W这个函数?
Error:
tl.visualize.W(network.all_params[0].eval(), second=10, saveable=True, shape=[28, 28],
AttributeError: module 'tensorlayer.visualize' has no attribute 'W'

**Comment by zsdonghao** [comment]
W be changed to draw_weights in the latest version of TL
