### ISSUE TITLE
ch 6.4 p162 line 11 为什么这里用了tl.layers.set_name_reuse(reuse)，而官方例子却没有用？

### ISSUE THREAD

**Issue by arisliang** [tensorlayer/chinese-book#21]
为什么在官方例子(https://github.com/tensorlayer/tensorlayer/blob/master/example/tutorial_generate_text.py) 没有`tl.layers.set_name_reuse(reuse)`测试也可以跑？

**Comment by wagamamaz** [comment]
Because, 1.8.1 version removes the use of global variables, `tl.layers.set_name_reuse(reuse)` is not longer require, and we can use TensorFlow only to control the reuse.

https://github.com/tensorlayer/tensorlayer/releases/tag/1.8.1

**Comment by arisliang** [comment]
I printed out the version while running official example:
tf version: 1.6.0
tl version: 1.8.0

Not 1.8.1 but still works.
Or at least I thought I printed it:
`print('tf version:', tf.VERSION)`
`print('tl version:',tl.__version__)`

**Comment by arisliang** [comment]
After pull the latest official example's repo, and upgraded pip installation to 1.8.1, it's shown 1.8.1. Perhaps previously it shows 1.8.0, but actually it contains the fix already.
