### ISSUE TITLE
建议: 下个版本增加seq2seq的章节

### ISSUE THREAD

**Issue by arisliang** [tensorlayer/chinese-book#28]
希望下个版本的书能够包括. seq2seq还是挺基本和重要的.
不知道有没有下个版本的计划?

**Comment by zsdonghao** [comment]
收到。

第二版通常是一年后才能出版的，不过我们在第二印上改了不少，比如Word Embedding基本重新写了。之后再印，可以考虑把seq2seq加上。

**Comment by arisliang** [comment]
好, 期待!
