### ISSUE TITLE
suppress_stdout with AttributeError: module 'tensorlayer' has no attribute 'ops'

### ISSUE THREAD

**Issue by arisliang** [tensorlayer/chinese-book#3]
```
import tensorflow as tf
import tensorlayer as tl

print("You can see me")
with tl.ops.suppress_stdout():
    print("You can't see me") # build your graphs here
print("You can see me")
```

Above code doesn't work in pycharm.

Is there any prerequisite for this to work?

I also raised in the tricks's own repo (https://github.com/wagamamaz/tensorlayer-tricks/issues/3). Just to put here as well, because here's the source I tried.

**Comment by zsdonghao** [comment]
TensorLayer uses logging instead of print() to output logs in the latest version, and `tl.ops` is removed in 1.8.0rc version. https://github.com/tensorlayer/tensorlayer/releases

**Comment by arisliang** [comment]
Changed tl.ops to tl.utils:
`with tl.utils.suppress_stdout():`
It gives:
> AttributeError: module 'tensorlayer.utils' has no attribute 'suppress_stdout'

**Comment by zsdonghao** [comment]
yes, this API has been removed, to control the logging of TensorLayer in 1.8.0rc, you can use python `logging`.

**Comment by arisliang** [comment]
Oh yea, that makes sense. Though this api is quite convenient, there might be ease-of-use value in it compared with python `logging`. For advanced logging control, to use python `logging` is fine.
