### ISSUE TITLE
TensorLayer书 第一印 第50页：当is_train为True，应该是为False吧

### ISSUE THREAD

**Issue by arisliang** [tensorlayer/chinese-book#4]
当is_train为False, DropoutLayer会被自动忽略。

**Comment by zsdonghao** [comment]
@arisliang 当is_train为False，DropoutLayer是要被忽略的，请看第51页，定义了训练和测试两个inference。

**Comment by arisliang** [comment]
是，51页代码是对的。可能正文笔误。

**Comment by zsdonghao** [comment]
噢，看到那个地方了～ 谢谢提醒
