### ISSUE TITLE
TensorLayer 书第50页, is_fix表示它的概率不保存在all_drop

### ISSUE THREAD

**Issue by arisliang** [tensorlayer/chinese-book#5]
应该是is_fix为True时，不保存在all_drop吧？
这样会造成tl.utils.dict_to_one(network.all_drop)和feed_dict.update(dp_dict)的技巧无效。这样理解对吗？

**Comment by zsdonghao** [comment]
是的，当用`is_fix=True`，我们不需要使用`tl.utils.dict_to_one(network.all_drop)`了。
