### ISSUE TITLE
[ch3.3 p61 line 14]为什么recon_layer1.all_layers[-2]没有返回layer类而是返回tensor?

### ISSUE THREAD

**Issue by arisliang** [tensorlayer/chinese-book#7]
我理解all_layers用index获得特定层，那么为什么取得的结果是tensor而不是layer呢？

**Comment by zsdonghao** [comment]
all_layers 里面是每一个layer的 outputs，所以不是 Layer 类，而是tensor。

可参见Layer设计：
http://tensorlayer.readthedocs.io/en/latest/modules/layers.html#a-simple-layer
http://tensorlayer.readthedocs.io/en/latest/modules/layers.html#your-dense-layer

**Comment by arisliang** [comment]
naming跟直观有点不一样. 如果是outputs，那么似乎叫all_outputs会比较好.
